language: node_js

# Sync to `process.versions.node` in the Electron dev console
# Currently: Electron 2.0
node_js: "8.9.3"

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_success: never
    on_failure: change
